"""Rings router — /api/rings endpoints."""

import json
import os
from typing import List, Optional

from fastapi import APIRouter, HTTPException
from api.schemas import RingListItem, RingDetail, GraphData, InvestigationResponse

DATA_DIR   = os.path.join(os.path.dirname(__file__), "..", "..", "data")
RINGS_PATH = os.path.join(DATA_DIR, "rings.json")
HERO_PATH  = os.path.join(DATA_DIR, "hero_accounts.json")

router = APIRouter(prefix="/api/rings", tags=["rings"])


def _load_rings():
    if not os.path.exists(RINGS_PATH):
        raise HTTPException(status_code=503,
                            detail="Detection pipeline has not run yet.")
    with open(RINGS_PATH) as f:
        return json.load(f)


def _get_ring(ring_id: str):
    rings = _load_rings()
    for ring in rings:
        if ring["ring_id"] == ring_id:
            return ring
    raise HTTPException(status_code=404, detail=f"Ring {ring_id} not found.")


@router.get("", response_model=List[RingListItem])
def list_rings():
    """List all detected rings, sorted by risk score descending."""
    rings  = _load_rings()
    result = []
    for ring in rings:
        top_evidence = ring["evidence"][0]["type"] if ring["evidence"] else None
        result.append(RingListItem(
            ring_id=ring["ring_id"],
            risk_score=ring["risk_score"],
            risk_band=ring["risk_band"],
            account_count=ring["account_count"],
            evidence_count=ring["evidence_count"],
            top_evidence_type=top_evidence,
            if_score=ring.get("if_score", 0),
            rule_score=ring.get("rule_score", 0),
            xgb_score=ring.get("xgb_score"),
        ))
    return sorted(result, key=lambda x: x.risk_score, reverse=True)


@router.get("/hero")
def get_hero_ring():
    """
    Return the hero demo ring — a deterministic, hand-verified ring
    combining all major fraud signals. Reliably appears in every pipeline run.
    """
    if not os.path.exists(HERO_PATH):
        raise HTTPException(status_code=404,
                            detail="Hero case not found. Run the data generator first.")
    with open(HERO_PATH) as f:
        hero_data = json.load(f)
    hero_members = set(hero_data.get("members", []))

    rings = _load_rings()
    best_ring  = None
    best_overlap = 0
    for ring in rings:
        overlap = len(set(ring["accounts"]) & hero_members)
        if overlap > best_overlap:
            best_overlap = overlap
            best_ring    = ring

    if best_ring is None:
        raise HTTPException(status_code=404,
                            detail="Hero ring not detected. Pipeline may need rerun.")

    return {
        **best_ring,
        "is_hero":     True,
        "hero_overlap": best_overlap,
        "hero_members": list(hero_members),
    }


@router.get("/{ring_id}", response_model=RingDetail)
def get_ring(ring_id: str):
    """Full evidence object for one ring."""
    ring     = _get_ring(ring_id)
    features = ring.get("features", {})
    return RingDetail(
        ring_id=ring["ring_id"],
        risk_score=ring["risk_score"],
        risk_band=ring["risk_band"],
        accounts=ring["accounts"],
        account_count=ring["account_count"],
        account_details=ring.get("account_details", []),
        evidence=ring.get("evidence", []),
        evidence_count=ring.get("evidence_count", 0),
        if_score=ring.get("if_score", 0),
        rule_score=ring.get("rule_score", 0),
        xgb_score=ring.get("xgb_score"),
        features=features,
    )


@router.get("/{ring_id}/graph", response_model=GraphData)
def get_ring_graph(ring_id: str):
    """Node/edge list scoped to one ring, for the graph UI."""
    ring  = _get_ring(ring_id)
    graph = ring.get("graph", {"nodes": [], "edges": []})
    return GraphData(
        nodes=graph.get("nodes", []),
        edges=graph.get("edges", []),
    )


@router.post("/{ring_id}/investigate", response_model=InvestigationResponse)
async def investigate_ring(ring_id: str):
    """Trigger LLM investigation for one ring. Returns analyst write-up."""
    ring = _get_ring(ring_id)
    from llm.investigator import investigate
    result = await investigate(ring)
    return InvestigationResponse(
        ring_id=ring_id,
        investigation=result["investigation"],
        model_used=result["model_used"],
        evidence_grounded=True,
        disclaimer=(
            "This investigation is generated by an AI model and is grounded "
            "solely in the structured evidence above. It does not constitute "
            "a definitive fraud determination. All flagged rings require "
            "human analyst review before any action is taken."
        ),
    )
