"""
Ground-truth type boundary for the real-time detection pipeline.

DESIGN INTENT:
  This module defines the PublicEvent type — the ONLY type that may cross
  the API ingestion boundary into the detection pipeline (feature extraction,
  XGBoost, Isolation Forest, rule scoring, risk engine, evidence builder,
  alert generation, LLM investigator).

GROUND-TRUTH SEPARATION (structural, not just conventional):
  - PublicEvent has NO label field (no is_fraud, no ring_id, no ring_type).
  - The scenario generator may internally track ScenarioEventMeta for its
    own bookkeeping and for evaluation comparison. That metadata is consumed
    ONLY by:
      * evaluation/evaluator.py (reads labels.csv)
      * ml/train.py (reads labels.csv for supervised training split)
    It NEVER reaches:
      * detection/feature_extractor.py
      * detection/scorer.py (XGBoost, IF, rule scoring)
      * detection/evidence_builder.py
      * api/routers/events.py
      * llm/investigator.py

  A future developer who wants to introduce leakage would have to explicitly
  add a label field to PublicEvent AND pass it through to the pipeline —
  this design makes the boundary visible and requires active circumvention.

AUDIT CHECKPOINT:
  grep -r "is_fraud_ring_member\|ring_id\|ring_type" backend/detection/
  Should return only graph_builder.py (node attributes for display/debug),
  never feature_extractor.py, scorer.py, or evidence_builder.py.
"""

from dataclasses import dataclass, field
from typing import Optional
from datetime import datetime


@dataclass
class PublicEvent:
    """
    A payment event as it enters the detection pipeline.

    Contains ONLY information available in real-time from the payment system.
    No fraud labels, no ring IDs, no ground-truth annotations of any kind.

    All fields may be None if the data is not available for a given event
    (e.g. device_id may not be present for API-based payments).
    """
    # Unique event identifier (generated by the ingestion layer if not provided)
    event_id: str

    # Transaction parties
    buyer_id: str
    merchant_id: str

    # Transaction details
    amount: float
    timestamp: datetime
    txn_type: str = "purchase"  # "purchase" | "refund"
    is_refund: bool = False

    # Infrastructure signals (may be None if not captured)
    device_id: Optional[str] = None
    ip_id: Optional[str] = None

    # Source: "manual" (judge-submitted) | "scenario" (simulator-generated) | "batch" (pipeline)
    # Note: source is metadata about HOW the event arrived, not about fraud.
    # It is used only for UI display (stream labeling) and logging — never for scoring.
    source: str = "manual"

    def __post_init__(self):
        # Defensive: raise if anyone tries to smuggle label fields in
        assert not hasattr(self, "is_fraud"), "PublicEvent must not carry fraud labels"
        assert not hasattr(self, "ring_id"), "PublicEvent must not carry ring IDs"
        assert not hasattr(self, "ring_type"), "PublicEvent must not carry ring type"


@dataclass
class ScenarioEventMeta:
    """
    Internal metadata kept by the scenario generator.
    NEVER passed to the detection pipeline.
    Used only by: evaluation/evaluator.py and ml/train.py.
    """
    event_id: str
    scenario_id: str
    scenario_type: str          # "CoordinatedRing" | "RefundFarming" | etc.
    is_fraud: bool              # ground truth label
    ring_id: Optional[str] = None  # internal ring grouping for evaluation


class EventIngestBoundary:
    """
    The type barrier between the scenario generator and the detection pipeline.

    Use this class to strip ScenarioEventMeta from events before they
    enter any detection/scoring/evidence code.

    Example:
        public_event = EventIngestBoundary.to_public(raw_event)
        # public_event has NO metadata about whether this is fraud
        result = detection_pipeline.process(public_event)
    """

    @staticmethod
    def to_public(
        buyer_id: str,
        merchant_id: str,
        amount: float,
        timestamp: datetime,
        txn_type: str = "purchase",
        is_refund: bool = False,
        device_id: Optional[str] = None,
        ip_id: Optional[str] = None,
        source: str = "manual",
    ) -> "PublicEvent":
        """
        Construct a PublicEvent. This is the ONLY way events enter the pipeline.
        Call this at the API boundary — never pass ScenarioEventMeta here.
        """
        import uuid
        return PublicEvent(
            event_id=str(uuid.uuid4()),
            buyer_id=buyer_id,
            merchant_id=merchant_id,
            amount=amount,
            timestamp=timestamp,
            txn_type=txn_type,
            is_refund=is_refund,
            device_id=device_id,
            ip_id=ip_id,
            source=source,
        )
